In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df1=pd.read_csv('data/train/2020-05-15-US-MTV-1/GooglePixel4XL/ground_truth.csv')

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3362 entries, 0 to 3361
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   MessageType       3362 non-null   object
 1   Provider          3362 non-null   object
 2   LatitudeDegrees   3362 non-null   float64
 3   LongitudeDegrees  3362 non-null   float64
 4   AltitudeMeters    0 non-null      float64
 5   SpeedMps          3362 non-null   float64
 6   AccuracyMeters    3362 non-null   float64
 7   BearingDegrees    3362 non-null   float64
 8   UnixTimeMillis    3362 non-null   int64
dtypes: float64(6), int64(1), object(2)
memory usage: 236.5+ KB

In [5]:
df1.describe()

,LatitudeDegrees,LongitudeDegrees,AltitudeMeters,SpeedMps,AccuracyMeters,BearingDegrees,UnixTimeMillis
count,3362.000000,3362.000000,0.0,3362.000000,3.362000e+03,3362.000000,3.362000e+03
mean,37.451073,-122.198970,NaN,18.451566,1.000000e-01,221.201778,1.589575e+12
std,0.086426,0.136324,NaN,13.183911,2.359575e-15,105.696572,9.706701e+05
min,37.332918,-122.433182,NaN,0.000000,1.000000e-01,0.223541,1.589574e+12
25%,37.401378,-122.331052,NaN,0.003546,1.000000e-01,92.968930,1.589575e+12
50%,37.416619,-122.135710,NaN,25.870860,1.000000e-01,281.457945,1.589575e+12
75%,37.502540,-122.082065,NaN,29.177857,1.000000e-01,316.725237,1.589576e+12
max,37.633192,-122.058927,NaN,37.115963,1.000000e-01,359.917050,1.589577e+12

Zieldaten

In [6]:
df2=pd.read_csv('data/train/2020-05-15-US-MTV-1/GooglePixel4XL/device_imu.csv')

In [11]:
df2.info()
df2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 734856 entries, 0 to 734855
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   MessageType    734856 non-null  object
 1   utcTimeMillis  734856 non-null  int64
 2   MeasurementX   734856 non-null  float64
 3   MeasurementY   734856 non-null  float64
 4   MeasurementZ   734856 non-null  float64
 5   BiasX          734856 non-null  float64
 6   BiasY          734856 non-null  float64
 7   BiasZ          734856 non-null  float64
dtypes: float64(6), int64(1), object(1)
memory usage: 44.9+ MB

,MessageType,utcTimeMillis,MeasurementX,MeasurementY,MeasurementZ,BiasX,BiasY,BiasZ
0,UncalAccel,1589573679447,0.237913,9.250001,1.784781,0.00000,0.000000,0.00000
1,UncalGyro,1589573679450,-0.022198,0.004974,0.014298,0.00000,0.000000,0.00000
2,UncalMag,1589573679450,2.812906,-37.320263,-1.189655,74.85504,-10.046193,-44.48028
3,UncalAccel,1589573679457,0.134411,9.673122,1.313673,0.00000,0.000000,0.00000
4,UncalMag,1589573679460,2.601327,-37.849490,-0.733490,74.85504,-10.046193,-44.48028

In [9]:
df3=pd.read_csv('data/train/2020-05-15-US-MTV-1/GooglePixel4XL/device_gnss.csv')

In [12]:
df3.info()
df3.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90153 entries, 0 to 90152
Data columns (total 47 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   MessageType                                90153 non-null  object
 1   utcTimeMillis                              90153 non-null  int64
 2   TimeNanos                                  90153 non-null  int64
 3   LeapSecond                                 0 non-null      float64
 4   FullBiasNanos                              90153 non-null  int64
 5   BiasNanos                                  90153 non-null  float64
 6   BiasUncertaintyNanos                       90153 non-null  float64
 7   DriftNanosPerSecond                        90153 non-null  float64
 8   DriftUncertaintyNanosPerSecond             90153 non-null  float64
 9   HardwareClockDiscontinuityCount            90153 non-null  int64
 10  Svid                                       90153 non-null  int64
 11  TimeOffsetNanos                            90153 non-null  float64
 12  State                                      90153 non-null  int64
 13  ReceivedSvTimeNanos                        90153 non-null  int64
 14  ReceivedSvTimeUncertaintyNanos             90153 non-null  int64
 15  Cn0DbHz                                    90153 non-null  float64
 16  PseudorangeRateMetersPerSecond             90153 non-null  float64
 17  PseudorangeRateUncertaintyMetersPerSecond  90153 non-null  float64
 18  AccumulatedDeltaRangeState                 90153 non-null  int64
 19  AccumulatedDeltaRangeMeters                90153 non-null  float64
 20  AccumulatedDeltaRangeUncertaintyMeters     90153 non-null  float64
 21  CarrierFrequencyHz                         90153 non-null  float64
 22  MultipathIndicator                         90153 non-null  int64
 23  ConstellationType                          90153 non-null  int64
 24  CodeType                                   90153 non-null  object
 25  ChipsetElapsedRealtimeNanos                90153 non-null  int64
 26  ArrivalTimeNanosSinceGpsEpoch              90153 non-null  int64
 27  RawPseudorangeMeters                       90153 non-null  float64
 28  RawPseudorangeUncertaintyMeters            90153 non-null  float64
 29  SignalType                                 90153 non-null  object
 30  ReceivedSvTimeNanosSinceGpsEpoch           90153 non-null  int64
 31  SvPositionXEcefMeters                      90153 non-null  float64
 32  SvPositionYEcefMeters                      90153 non-null  float64
 33  SvPositionZEcefMeters                      90153 non-null  float64
 34  SvElevationDegrees                         90153 non-null  float64
 35  SvAzimuthDegrees                           90153 non-null  float64
 36  SvVelocityXEcefMetersPerSecond             90153 non-null  float64
 37  SvVelocityYEcefMetersPerSecond             90153 non-null  float64
 38  SvVelocityZEcefMetersPerSecond             90153 non-null  float64
 39  SvClockBiasMeters                          90153 non-null  float64
 40  SvClockDriftMetersPerSecond                90153 non-null  float64
 41  IsrbMeters                                 90153 non-null  float64
 42  IonosphericDelayMeters                     90153 non-null  float64
 43  TroposphericDelayMeters                    90153 non-null  float64
 44  WlsPositionXEcefMeters                     90153 non-null  float64
 45  WlsPositionYEcefMeters                     90153 non-null  float64
 46  WlsPositionZEcefMeters                     90153 non-null  float64
dtypes: float64(30), int64(14), object(3)
memory usage: 32.3+ MB

,MessageType,utcTimeMillis,TimeNanos,LeapSecond,FullBiasNanos,BiasNanos,BiasUncertaintyNanos,DriftNanosPerSecond,DriftUncertaintyNanosPerSecond,HardwareClockDiscontinuityCount,...,SvVelocityYEcefMetersPerSecond,SvVelocityZEcefMetersPerSecond,SvClockBiasMeters,SvClockDriftMetersPerSecond,IsrbMeters,IonosphericDelayMeters,TroposphericDelayMeters,WlsPositionXEcefMeters,WlsPositionYEcefMeters,WlsPositionZEcefMeters
0,Raw,1589573679445,9825908000000,NaN,-1273599071537525599,0.414394,29.760322,0.058358,10.712862,6,...,-17.054923,3156.993021,-136834.550923,-0.001592,0.0,4.733301,3.394811,-2.693907e+06,-4.297452e+06,3.854203e+06
1,Raw,1589573679445,9825908000000,NaN,-1273599071537525599,0.414394,29.760322,0.058358,10.712862,6,...,1097.133346,2801.579397,-81575.252587,-0.002044,0.0,3.933861,2.831474,-2.693907e+06,-4.297452e+06,3.854203e+06
2,Raw,1589573679445,9825908000000,NaN,-1273599071537525599,0.414394,29.760322,0.058358,10.712862,6,...,-2177.983493,1370.434597,35245.121840,-0.002146,0.0,5.685666,4.716946,-2.693907e+06,-4.297452e+06,3.854203e+06
3,Raw,1589573679445,9825908000000,NaN,-1273599071537525599,0.414394,29.760322,0.058358,10.712862,6,...,222.719634,-841.694753,79527.095297,0.003038,0.0,5.565332,4.452569,-2.693907e+06,-4.297452e+06,3.854203e+06
4,Raw,1589573679445,9825908000000,NaN,-1273599071537525599,0.414394,29.760322,0.058358,10.712862,6,...,293.424387,302.063410,-47469.325722,0.000590,0.0,4.065440,3.035621,-2.693907e+06,-4.297452e+06,3.854203e+06

utcTimeMillis is in df2 and df3

In [13]:
print(df2.utcTimeMillis.nunique(), df3.utcTimeMillis.nunique())

688437 3362